---
title: "Preliminaries"
description: "Who I am and how I'm approaching the competition"
date: 2026-08-29
categories:
  - introduction
  - challenge 2026
---

## whoami

Hi! I'm Forrest and for whatever reason you've stumbled onto my Virtual Cell Challenge blog.
I made a pivot from physics and neuromorphic computing to biology and cell reprogramming a few years ago.
For the last couple of years I've been working on analyzing perturbation screens and trying to find reliable ways
to nominate cell reprogramming targets.
That turns out to be a pretty hard problem and in the process I'm continually learning new things about biology,
statistics and machine learning.
To keep that process going, I'm joining the Virtual Cell Challenge.

## How I'm approaching the Virtual Cell Challenge

First, I am not alone. My friend Alex and I are a two-person team.
As individuals we can't compete with larger teams on resources, so the goal here is to carefully wade into this year's challenge and
look for novel and cheap ideas that we can try.
The best way to learn is not just by doing, but by doing carefully, and writing about the process is a way to ensure that happens.
Hopefully in doing that, we'll kick off some worthwhile conversations with everyone else.

Broadly, I'm organizing my work into four stages:

* Exploring the Data - For the first week or two I'll be writing about the provided and linked datasets and the methods
used to produce them.
The material here will be more biology and sequencing heavy but if you want to make a good model, you need to understand your data.
* Baselines - One of the themes of virtual cell modeling so far is that simple baselines are tough to beat.
A lot of that debate centers on what you measure and more careful evaluations have shown that deep learning
models may have the edge.
The point remains though that simple interpretable models can be competitive if they are carefully geared to the problem
at hand.
I'll start with simple linear models and examine the evaluation metrics carefully.
Looking at these should occupy early September.
* Beyond Linear Models - Can we use the successes and failures of our nice interpretable baselines to develop a family
of slightly more advanced models that include machine learning in precisely targeted ways? This should close out September.
* Modern Models - Part of the goal of all of this is to learn about the modern approaches to the virtual cell:
transformers, flow matching, optimal transport etc. I'll spend the last month of the competition writing about and playing
with these approaches.

If that sounds interesting, I hope you'll follow along.
